// @generated by protoc-gen-connect-es v0.8.3 with parameter "target=ts"
// @generated from file v1/greet.proto (package greet.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GreetRequest, GreetResponse, GreetStreamRequest, GreetStreamResponse } from "./greet_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service greet.v1.GreetService
 */
export const GreetService = {
  typeName: "greet.v1.GreetService",
  methods: {
    /**
     * @generated from rpc greet.v1.GreetService.Greet
     */
    greet: {
      name: "Greet",
      I: GreetRequest,
      O: GreetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service greet.v1.GreetStreamService
 */
export const GreetStreamService = {
  typeName: "greet.v1.GreetStreamService",
  methods: {
    /**
     * @generated from rpc greet.v1.GreetStreamService.GreetStream
     */
    greetStream: {
      name: "GreetStream",
      I: GreetStreamRequest,
      O: GreetStreamResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

